#!/usr/bin/perl -w

use strict;
use Config::Tiny;

my ($action, $param) = @ARGV;
die "usage: $0 <action> <parameter>\n" if not $param;

my $conffile = $ENV{HOME} . '/.iterm-launcher.conf';
my $defparam = '_';
my $config = {};
if (-f $conffile) {
    $config = Config::Tiny->read($conffile);
}

my @comm = ();

if ($config->{$action}->{$param} || $config->{$action}->{_}) {
    my $comm = $config->{$action}->{$param} || $config->{$action}->{_};
    $comm =~ s#^~/#$ENV{HOME}/#;
    $comm =~ s/%s/$param/g;
    @comm = split(' ', $comm);
} elsif ($action eq 'ssh') {
    push(@comm, '/usr/bin/ssh');
    if ($param =~ /\[(.*?)\]:(\d+)/) {
        push(@comm, ('-p', $2, $1));
    } else {
        push(@comm, $param);
    }
}
die "Don't know what to do" if not @comm;

system(@comm) == 0
    or die "Command returned error: $?";
exit 0;
